---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    config:
      config: "./.eslintrc"
    enabled: true
    channel: "eslint-2"
    checks:
      import/no-unresolved:
        enabled: false
      comma-dangle:
        enabled: false
      TODO:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- test/
- build/
- tools/
- src/mockData
